[pytest]
DJANGO_SETTINGS_MODULE = pexp.tests.settings
pythonpath = . .. ../src
django_find_project = false
testpaths = tests
python_files = test*.py
python_classes = Test*
python_functions = test_*
addopts = -p no:playwright
